version: '3.3'
services:
    api:
      build: ./api
      image: erwankerbrat/api
      ports:
        - "1234:5000" 
      environment:
        DATABASE_URL: "mysql://root:rootpassword@db:3306/db_test"
    db:
      image: mysql:5.7
      volumes:
       - ./data-init:/docker-entrypoint-initdb.d  
      environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: db_test
          MYSQL_USER: username
          MYSQL_PASSWORD: password

    dbadmin:
      image: phpmyadmin/phpmyadmin:edge-4.9
      environment:
          PMA_ARBITRARY: 1
          PMA_HOST: db
          #MPA_PORT: 3306
          PMA_USER: root 
          PMA_PASSWORD: rootpassword 
      ports:
        - "1235:80" 